; homez.g
; called to home the Z axis
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
G1 H2 Z5 F10800  ; lift Z relative to current position
G90
G1 X100 Y100 F5000
G30
G29 S1
;Set Extrude 0
T0

