; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)

T-1
M98 P"homex.g"
M98 P"homey.g"
M98 P"homez.g"