; homez.g
; called to home the Z axis
;Set Extrude 0
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa central)
M906 X1200 Y1200 Z1200 E1800 I30             
M201 X1500.00 Y1500.00 Z5.00 E1000.00  
M915 P0.2:0.3 S3 F0 H320 R0
M913 Z70
M564 H0 S0
G91              ; relative positioning
G1 H1 Z200 F300
G90
M913 Z100
M564 H1 S1
M201 X500.00 Y500.00 Z5.00 E1000.00  
