; homey.g
; called to home the Y axis
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
;Setting for stall detection endstop
M201 X1500.00 Y1500.00 Z5.00 E1000.00  
M906 X1200 Y1200 Z1200 E1800 I30             
M915 P0.1 S1 F0 H190 R0
M201 Y500
;reduce current motor
M913 Y75
;allow movment outside
M564 H0 S0
G91               ; relative positioning
G1 H1 Y1 F1000         ;free fase movment            
G1 H1 Y-310 F2500 ; move slowly to Y axis endstop once more (second pass)
G90               ; absolute positioning
M913 Y100         ; reset current motor
M201 Y1500
M564 H1 S1
M201 X500.00 Y500.00 Z5.00 E1000.00  

