; homex.g
; called to home the Y axis
;Setting for stall detection endstop
M201 X1500.00 Y1500.00 Z5.00 E1000.00  
M906 X1200 Y1200 Z1200 E1800 I30             
M915 P0.0 S3 F0 H200 R0
;reduce current motor
M913 X70
;allow movment outside
M564 H0 S0
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
G91               ; relative positioning
G1 H1 X1 F1000
G1 H1 X-310 F4000  ; move slowly to Y axis endstop once more (second pass)
G90               ; absolute positioning
;reset current motor
M913 X100
M564 H1 S1
M201 X500.00 Y500.00 Z5.00 E1000.00  
