; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Jul 23 2021 18:56:12 GMT+0200 (Ora legale dell’Europa centrale)
M564 H0 S0 
M913 Z100 ; drop motor current to 70%
G91                     ; relative positioning
G1 H4 Z200 F2200         ; lift Z relative to current position
G1 H1 X-240 Y-285 F1800 ; move quickly to X and Y axis endstops and stop there (first pass)
G1 H1 X5 Y5 F10800      ; go back a few mm
G1 H1 X-240 Y-285 F360  ; move slowly to X and Y axis endstops once more (second pass)         
G90                     ; absolute positioning
G1 X112 Y119 F4000
M913 Z100
G30 
;G92 Z200                ; set Z position to axis maximum (you may want to adjust this)

; Uncomment the following lines to lift Z after probing
;G91                    ; relative positioning
;G1 Z4 F180             ; lift Z relative to current position
;G90                    ; absolute positioning


