; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
M117 "TILT PIANO"
M118 P0 S"TILT PIANO" L3
T-1
M561 ; clear any bed transform
G29 S2  ; Disable mesh bed compensation and clear the height map
G28
M18 C
while true
    G4 P400
	G30 P0 X0 Y20 Z-99999
	G4 P400
	G30 P1 X560 Y540 Z-99999 
	G4 P400
	G30 P2 X1050 Y20 Z-99999 S3
    if abs(move.calibration.initial.deviation) < 0.05 || iterations > 3
        break

G90                     ; absolute positioning
G1 X{move.axes[0].max/2} Y{move.axes[1].max} F6000      ; go Center of bed
G28 C
