; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Tue Jun 22 2021 12:31:59 GMT+0200 (Ora legale dell’Europa centrale)
T-1
M109 T0 S0
M109 T1 S0
M190 S0
M106 P0 S0 ;Turn-off fan 
M106 P1 S0 ;Turn-off fan 
M150 E0 R255 U0 B0 S78 P255
