;##FE31-H10E10-2506-001

; Miscellaneous
;T0                                       ; select first tool
if sensors.gpIn[7].value == 1 && sensors.gpIn[8].value == 1 && sensors.gpIn[9].value == 0 && sensors.gpIn[10].value == 0 && sensors.gpIn[11].value == 0
    M118 P0 S"No extruder in printer, please resolve conflict"
if sensors.gpIn[6].value == 1 && sensors.gpIn[7].value == 1
    M118 P0 S"Extruder T0 on TC"
    T0 P0
    G92 C60
if sensors.gpIn[6].value == 1 && sensors.gpIn[8].value == 1
    M118 P0 S"Extruder T1 on TC"
    T1 P0
    G92 C60
if sensors.gpIn[6].value == 1 && sensors.gpIn[9].value == 1
    M118 P0 S"Extruder T2 on TC"
    T2 P0
    G92 C60
if sensors.gpIn[6].value == 1 && sensors.gpIn[10].value == 1
    M118 P0 S"Extruder T3 on TC"
    T3 P0
    G92 C60
if sensors.gpIn[6].value == 1 && sensors.gpIn[11].value == 1
    M118 P0 S"Extruder T4 on TC"
    T4 P0
    G92 C60