; Nozzle sizes per slot — auto-generated by set-nozzle.g
; Non modificare manualmente: usare M98 P"set-nozzle.g" T{n} N{dia}
; Richiede che tool-profiles.g sia stato eseguito prima (dichiara i global)
set global.t0NozzleDia = 0.4
set global.t0PressAdv  = 0.060
set global.t1NozzleDia = 0.4
set global.t1PressAdv  = 0.060
set global.t2NozzleDia = 0.4
set global.t2PressAdv  = 0.060
set global.t3NozzleDia = 0.4
set global.t3PressAdv  = 0.060
set global.t4NozzleDia = 0.4
set global.t4PressAdv  = 0.060
