; set-nozzle.g — Cambia ugello su uno slot, calcola PA automaticamente, salva su disco
; Utilizzo: M98 P"set-nozzle.g" T{tool 0-4} N{diametro mm}
; Esempi:   M98 P"set-nozzle.g" T0 N0.6
;           M98 P"set-nozzle.g" T2 N0.4
;
; Diametri supportati con PA automatico: 0.25 / 0.4 / 0.6 / 0.8 / 1.0
; Per PA personalizzato: modificare global.paNozzleXX in tool-profiles.g

if !exists(param.T) || !exists(param.N)
    echo "Errore set-nozzle.g: parametri T (tool 0-4) e N (diametro ugello) obbligatori"
    M99

if param.T < 0 || param.T > 4
    echo "Errore set-nozzle.g: T deve essere 0-4"
    M99

; Calcola pressure advance dalla tabella lookup in tool-profiles.g
var newPA = global.paNozzle04
if param.N = 0.25
    set var.newPA = global.paNozzle025
elif param.N = 0.6
    set var.newPA = global.paNozzle06
elif param.N = 0.8
    set var.newPA = global.paNozzle08
elif param.N = 1.0
    set var.newPA = global.paNozzle10

; Aggiorna globals in memoria per lo slot specificato
if param.T = 0
    set global.t0NozzleDia = param.N
    set global.t0PressAdv  = var.newPA
elif param.T = 1
    set global.t1NozzleDia = param.N
    set global.t1PressAdv  = var.newPA
elif param.T = 2
    set global.t2NozzleDia = param.N
    set global.t2PressAdv  = var.newPA
elif param.T = 3
    set global.t3NozzleDia = param.N
    set global.t3PressAdv  = var.newPA
elif param.T = 4
    set global.t4NozzleDia = param.N
    set global.t4PressAdv  = var.newPA

; Persiste tutti gli ugelli su nozzle-sizes.g (riscrittura completa)
echo >"0:/sys/nozzle-sizes.g" "; Nozzle sizes per slot — auto-generated by set-nozzle.g"
echo >>"0:/sys/nozzle-sizes.g" "; Non modificare manualmente: usare M98 P""set-nozzle.g"" T{n} N{dia}"
echo >>"0:/sys/nozzle-sizes.g" "; Richiede che tool-profiles.g sia stato eseguito prima (dichiara i global)"
echo >>"0:/sys/nozzle-sizes.g" {"set global.t0NozzleDia = " ^ global.t0NozzleDia}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t0PressAdv  = " ^ global.t0PressAdv}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t1NozzleDia = " ^ global.t1NozzleDia}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t1PressAdv  = " ^ global.t1PressAdv}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t2NozzleDia = " ^ global.t2NozzleDia}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t2PressAdv  = " ^ global.t2PressAdv}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t3NozzleDia = " ^ global.t3NozzleDia}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t3PressAdv  = " ^ global.t3PressAdv}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t4NozzleDia = " ^ global.t4NozzleDia}
echo >>"0:/sys/nozzle-sizes.g" {"set global.t4PressAdv  = " ^ global.t4PressAdv}

; Applica PA aggiornato per tutti i tool presenti
M98 P"apply-nozzle-pa.g"

echo {"Ugello T" ^ param.T ^ " = " ^ param.N ^ "mm | PA = " ^ var.newPA ^ " — salvato."}
