name: Build DuetPi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Run the build process
      - name: Build image
        run: |
          mkdir out
          sudo ./build-docker.sh

      # Upload lite image
      - uses: actions/upload-artifact@v3
        with:
          name: DuetPi-lite
          path: deploy/image_*DuetPi-lite.img
          if-no-files-found: error

      # Upload main image
      - uses: actions/upload-artifact@v3
        with:
          name: DuetPi
          path: deploy/image_*DuetPi.img
          if-no-files-found: error

      # Upload factory image
      - uses: actions/upload-artifact@v3
        with:
          name: DuetPi-factory
          path: deploy/image_*DuetPi-factory.img
          if-no-files-found: error

