name: Build DuetPi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install dependencies and run the build process
      - name: Install dependencies
        run: |
          sudo apt-get install -y quilt parted debootstrap jq kpartx pigz

      # Run the build process
      - name: Build image
        run: |
          mkdir out
          sudo DEPLOY_COMPRESSION=none DEPLOY_DIR=./out ./build.sh

      # Upload lite image
      - uses: actions/upload-artifact@v3
        with:
          name: DuetPi-lite
          path: out/image_*DuetPi-lite.img

      # Upload main image
      - uses: actions/upload-artifact@v3
        with:
          name: DuetPi
          path: out/image_*DuetPi.img

      # Upload factory image
      - uses: actions/upload-artifact@v3
        with:
          name: DuetPi-factory
          path: out/image_*DuetPi-factory.img
