name: Build DuetPi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      pi-gen-upload-image:
        steps:
          - uses: usimd/pi-gen-action@v1
            id: build
            with:
              pi-gen-repository: Duet3D/DuetPi
              release: buster

          - uses: actions/upload-artifact@v3
            with:
              name: pi-gen-image
              path: ${{ steps.build.outputs.image-path }}

