name: Build DuetPi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Run the build process
      - name: Build image
        run: |
          mkdir out
          sudo ./build-docker.sh

      # Get the image date
      - name: Get image name
        run: |
          IMG_NAME=(deploy/image_*-DuetPi.zip)
          if [[ $IMG_NAME =~ ^deploy/image_(.*)-DuetPi.zip$ ]]; then
            echo "IMG_DATE=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "Error: Image not found!"
            exit 1
          fi

      # Make new release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.IMG_DATE }}
          prerelease: false
          title: "DuetPi ${{ env.IMG_DATE }} (buster)"
          files: deploy/image_*.zip

