name: Build DuetPi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get install -y qemu-user-static

      - name: Build image
        run: |
          sudo ./build-docker.sh

      - name: Get image date
        run: |
          IMG_NAME=(deploy/image_*-DuetPi-arm64.zip)
          if [[ $IMG_NAME =~ ^deploy/image_(.*)-DuetPi-arm64.zip$ ]]; then
            echo "IMG_DATE=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "Error: Image not found!"
            exit 1
          fi

      - name: Make new release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "bookworm-arm64-${{ env.IMG_DATE }}"
          prerelease: true
          title: "DuetPi ${{ env.IMG_DATE }} (bookworm-arm64)"
          files: deploy/image_*.zip

