name: Build DuetPi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Build image
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: DuetPi
          pi-gen-repository: Duet3D/DuetPi
          release: buster

      # Upload image
      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}

