name: Build DuetPi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          mkdir out
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo ./build-docker.sh

      - name: Get image date
        run: |
          IMG_NAME=(deploy/image_*-DuetPi.zip)
          if [[ $IMG_NAME =~ ^deploy/image_(.*)-DuetPi.zip$ ]]; then
            echo "IMG_DATE=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "Error: Image not found!"
            exit 1
          fi

      - name: Make new release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.IMG_DATE }}
          prerelease: true
          title: "DuetPi ${{ env.IMG_DATE }} (bullseye)"
          files: deploy/image_*.zip

